kind: Service
apiVersion: v1
metadata:
  name: facade-service
spec:
  type: NodePort
  selector:
    app: facade
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  externalIPs:
    - 1.2.4.120